### ISSUE TITLE
Support for YAML metadata blocks

### ISSUE THREAD

**Issue by offray** [pillar-markup/MicroDown#57]
I'm really glad to see microdown as a bridge between (a variant of a) Markdown syntax in the surface and the Pillar machinery in the back end, as it could lower/end the Grafoscopio reliance on external dependencies (ie. Pandoc, Lunamark) for markup conversions between Markdown and HTML/LaTeX/PDF. Thanks for microdown.

Several Markdown variants have adopted YAML metadata block (gfm shows them as tables, Zettlr, Pandoc, Jeykill and other static site generators use it to define even operations and properties of the exported documents once they become LaTeX, HTML and so on). Such blocks are at the beginning of the document containing between `---` the document metadata, like this:

```yaml
---
name: example
context:
  - type: feature request.
  - url: https://github.com/pillar-markup/MicroDown/issues/57
--- 
```
Can YAML metadata blocks support be added to microdown (or as a plugin), so YAML inside a microdown text can be converted to (Ordered) dictionaries in Pharo?

Thanks again.
